name = "Simplicial"
uuid = "bb1577d6-fed0-5ffd-8131-5296c7c3c7ad"
keywords = ["algebraic topology", "TDA", "Homology"]
license = "MIT"


[deps]
Combinatorics="861a8166-3701-5b0c-9a16-15d98fcdc6aa"
LightGraphs ="093fc24a-ae57-5d10-9952-331d41423f4d"
PyPlot="d330b81b-6aea-500a-939a-2ce795aea3ee"
IterTools="c8e1da08-722c-5040-9ed9-7db0dc04731e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1"
