name = "Simplicial"
uuid = "bb1577d6-fed0-5ffd-8131-5296c7c3c7ad"
keywords = ["algebraic topology", "TDA", "Homology"]
license = "MIT"
version = "0.1.1"


[deps]
SparseArrays="2f01184e-e22b-5df5-ae63-d93ebab69eaf"
DelimitedFiles="8bb1440f-4735-579b-a4ab-409b98df4dab"
Combinatorics="861a8166-3701-5b0c-9a16-15d98fcdc6aa"
LightGraphs ="093fc24a-ae57-5d10-9952-331d41423f4d"
PyPlot="d330b81b-6aea-500a-939a-2ce795aea3ee"
IterTools="c8e1da08-722c-5040-9ed9-7db0dc04731e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
[compat]
julia = "1"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
